name: Build, Test and Deploy React Application
# Controls when the action will run.
on:
 # Triggers the workflow on push or pull request events but only for the main branch
 push:
   branches: [ master ]
 pull_request:
   branches: [ master ]
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 deploy: 
  environment: 
   name: github-pages
   url: ${{steps.deployment.outputs.page_url}}
  runs-on: ubuntu-latest
  permissions: 
   pages: write
   id-token: write 
  needs: build_test
  steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
    
 build_test:
 # The type of runner that the job will run on
   runs-on: ubuntu-latest
   permissions:
    contents: write
   strategy:
     matrix:
       node-version: [21.x]
 # Steps represent a sequence of tasks that will be executed as part of the job
   steps:
   # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     - uses: actions/checkout@v2
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v2
       with:
         node-version: ${{ matrix.node-version }}
     - name: npm ci, build and test
       run: | 
        npm ci
        npm run jsdoc
        npm run build --if-present
        npm test 
     - name: Upload coverage reports to Codecov
       uses: codecov/codecov-action@v5
       with:
         token: ${{ secrets.CODECOV_TOKEN }}
     - name: Setup Pages
       id: pages
       uses: actions/configure-pages@v3
     - name: Upload artifact
       uses: actions/upload-pages-artifact@v3
       with:
        path: build
     - name: Athenticate with npm
       run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
     - name: Get latest NPM version
       id: npm_version
       run: |
        echo "remote_version=$(npm view integration-test-react-corentin-2026 version || echo 0.0.0)" >> $GITHUB_OUTPUT
     - name: Get local version
       id: local_version
       run: |
        echo "local_version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
     - name: Compare versions
       id: compare
       run: |
        if [ "${{ steps.local_version.outputs.local_version }}" != "${{ steps.npm_version.outputs.remote_version }}" ]; then
         echo "should_publish=true" >> $GITHUB_OUTPUT
        else
         echo "should_publish=false" >> $GITHUB_OUTPUT
        fi
     - name: Publish to NPM
       if: steps.compare.outputs.should_publish == 'true'
       run: npm publish --access public
       env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
 build-docker:
  runs-on: ubuntu-latest

  needs: build_test

  steps:
  - uses: actions/checkout@v4

  - name: Login Docker Hub
    uses: docker/login-action@v3
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  - name: Build frontend image
    run: |
      docker build \
        -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest \
        -f DockerfileReact .

  - name: Push frontend image
    run: |
      docker push \
        ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

  - name: Build backend image
    run: |
      docker build \
        -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest \
        -f server/DockerfilePython \
        ./server

  - name: Push backend image
    run: |
      docker push \
        ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest      


